# 03 — Data Preparation (Kedro + CRISP-DM)

In [1]:
# --- Inicializar Kedro sin magics ---
from pathlib import Path
from kedro.framework.session import KedroSession
from kedro.framework.startup import bootstrap_project

# localizar la raíz del proyecto subiendo hasta encontrar pyproject.toml
project_path = Path.cwd()
while project_path != project_path.parent and not (project_path / "pyproject.toml").exists():
    project_path = project_path.parent
assert (project_path / "pyproject.toml").exists(), f"No encuentro pyproject.toml desde {Path.cwd()}"

bootstrap_project(str(project_path))
session = KedroSession.create(project_path=str(project_path))
ctx = session.load_context()
catalog = ctx.catalog

print("Proyecto:", project_path)

[09/15/25 22:47:17] INFO     Using                                                                  ]8;id=86940;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\framework\project\__init__.py\__init__.py]8;;\:]8;id=256379;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\framework\project\__init__.py#270\270]8;;\
                             'c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\framework
                             \project\rich_logging.yml' as logging configuration.

[09/15/25 22:47:19] INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=200614;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=114508;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro_telemetry\plugin.py#243\243]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/configuration/telemetry.html

Proyecto: c:\Users\lttlk\Documents\Nueo\machinegame

In [2]:
# Diagnóstico rápido
import sys
try:
    import kedro
    print("Python:", sys.executable)
    print("Kedro:", kedro.__version__)
    print("Datasets (primeros 15):", list(catalog.list())[:15])
except Exception as e:
    print("No se pudo inspeccionar kedro:", e)

Python: c:\Users\lttlk\Documents\Nueo\.venv\Scripts\python.exe
Kedro: 1.0.0
No se pudo inspeccionar kedro: 'DataCatalogWithCatalogCommandsMixin' object has no attribute 'list'

In [3]:
# Helpers: cargar o reconstruir y reparación de encoding
from pathlib import Path
import pandas as pd

def load_or_build(name: str, pipe: str):
    """Intenta catalog.load(name); si falla, ejecuta el pipeline y vuelve a cargar."""
    try:
        return catalog.load(name)
    except Exception as e:
        print(f"[load_or_build] {name} no disponible o ilegible ({e}). Corriendo pipeline: {pipe} …")
        session.run(pipeline_name=pipe)
        return catalog.load(name)

def fix_reporting_csv_encoding(report_dir: Path | str = None, encoding_from: str = "latin1", encoding_to: str = "utf-8"):
    """Repara CSVs en 08_reporting que estén en ANSI/latin-1: reescribe en UTF-8.
    Si ya son UTF-8 válidos, los deja intactos.
    """
    if report_dir is None:
        report_dir = project_path / "data" / "08_reporting"
    report_dir = Path(report_dir)
    if not report_dir.exists():
        print("[fix_reporting_csv_encoding] No existe la carpeta:", report_dir)
        return

    fixed, skipped = [], []
    for p in report_dir.glob("*.csv"):
        try:
            _ = pd.read_csv(p, encoding=encoding_to, nrows=5)
            skipped.append(p.name)
        except Exception:
            try:
                df = pd.read_csv(p, encoding=encoding_from)
                df.to_csv(p, index=False, encoding=encoding_to)
                fixed.append(p.name)
            except Exception as e:
                print(f"[fix_reporting_csv_encoding] No se pudo reparar {p.name}: {e}")
    print("[fix_reporting_csv_encoding] Reparados (latin-1 -> utf-8):", fixed)
    print("[fix_reporting_csv_encoding] Ya estaban en utf-8:", skipped)

### Ejecutar pipeline de Data Preparation

In [4]:
session.run(pipeline_name="data_preparation")

[09/15/25 22:47:21] INFO     Kedro project machinegame                                               ]8;id=235685;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\framework\session\session.py\session.py]8;;\:]8;id=567408;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\framework\session\session.py#330\330]8;;\

                    INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=457891;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=692548;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro_telemetry\plugin.py#243\243]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/configuration/telemetry.html

[09/15/25 22:47:22] WARNING  Workflow tracking is disabled during partial pipeline runs (executed  ]8;id=709751;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro_viz\integrations\kedro\run_hooks.py\run_hooks.py]8;;\:]8;id=617391;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro_viz\integrations\kedro\run_hooks.py#135\135]8;;\
                             using --from-nodes, --to-nodes, --tags, --pipeline, and more).
                             `.viz/kedro_pipeline_events.json` will be created only during a full
                             kedro run. See issue
                             https://github.com/kedro-org/kedro-viz/issues/2443 for more details.

[09/15/25 22:47:23] INFO     Using synchronous mode for loading and saving data. Use the    ]8;id=981295;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\sequential_runner.py\sequential_runner.py]8;;\:]8;id=300966;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\sequential_runner.py#59\59]8;;\
                             --async flag for potential performance gains.
                             https://docs.kedro.org/en/stable/nodes_and_pipelines/run_a_pip
                             eline.html#load-and-save-asynchronously

                    INFO     Loading data from games_raw (CSVDataset)...                       ]8;id=232602;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=674259;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Loading data from params:prep.drop_duplicates (MemoryDataset)...  ]8;id=563724;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=238569;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Loading data from params:prep.drop_all_null_cols                  ]8;id=362047;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=752147;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\
                             (MemoryDataset)...

                    INFO     Loading data from params:prep.fillna_strategy (MemoryDataset)...  ]8;id=260154;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=869105;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Running node: clean_games: clean_dataset() ->                              ]8;id=466400;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\pipeline\node.py\node.py]8;;\:]8;id=989389;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\pipeline\node.py#420\420]8;;\

                    INFO     Saving data to games_clean (ParquetDataset)...                    ]8;id=519824;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=564481;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1006\1006]8;;\

                    INFO     Completed node: clean_games                                              ]8;id=32164;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py\runner.py]8;;\:]8;id=277429;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py#245\245]8;;\

                    INFO     Completed 1 out of 6 tasks                                               ]8;id=394019;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py\runner.py]8;;\:]8;id=820936;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py#246\246]8;;\

                    INFO     Loading data from steam_raw (CSVDataset)...                       ]8;id=476615;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=715300;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Loading data from params:prep.drop_duplicates (MemoryDataset)...  ]8;id=294080;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=633953;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Loading data from params:prep.drop_all_null_cols                  ]8;id=599404;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=197570;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\
                             (MemoryDataset)...

                    INFO     Loading data from params:prep.fillna_strategy (MemoryDataset)...  ]8;id=730581;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=990850;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Running node: clean_steam: clean_dataset() ->                              ]8;id=502100;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\pipeline\node.py\node.py]8;;\:]8;id=76451;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\pipeline\node.py#420\420]8;;\

                    INFO     Saving data to steam_clean (ParquetDataset)...                    ]8;id=95170;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=993788;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1006\1006]8;;\

[09/15/25 22:47:24] INFO     Completed node: clean_steam                                              ]8;id=143162;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py\runner.py]8;;\:]8;id=517221;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py#245\245]8;;\

                    INFO     Completed 2 out of 6 tasks                                               ]8;id=906739;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py\runner.py]8;;\:]8;id=531962;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py#246\246]8;;\

                    INFO     Loading data from vg_sales_raw (CSVDataset)...                    ]8;id=869632;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=746963;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Loading data from params:prep.drop_duplicates (MemoryDataset)...  ]8;id=476044;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=229385;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Loading data from params:prep.drop_all_null_cols                  ]8;id=603128;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=952525;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\
                             (MemoryDataset)...

                    INFO     Loading data from params:prep.fillna_strategy (MemoryDataset)...  ]8;id=112448;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=38434;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Running node: clean_vg_sales: clean_dataset() ->                           ]8;id=57178;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\pipeline\node.py\node.py]8;;\:]8;id=960483;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\pipeline\node.py#420\420]8;;\

                    INFO     Saving data to vg_sales_clean (ParquetDataset)...                 ]8;id=872260;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=225085;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1006\1006]8;;\

                    INFO     Completed node: clean_vg_sales                                           ]8;id=792199;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py\runner.py]8;;\:]8;id=933660;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py#245\245]8;;\

                    INFO     Completed 3 out of 6 tasks                                               ]8;id=487954;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py\runner.py]8;;\:]8;id=979691;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py#246\246]8;;\

                    INFO     Loading data from games_clean (ParquetDataset)...                 ]8;id=984622;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=230937;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Running node: features_games: add_basic_features() ->                      ]8;id=766618;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\pipeline\node.py\node.py]8;;\:]8;id=567772;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\pipeline\node.py#420\420]8;;\

                    INFO     Saving data to games_prepared (ParquetDataset)...                 ]8;id=839709;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=112035;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1006\1006]8;;\

                    INFO     Completed node: features_games                                           ]8;id=357491;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py\runner.py]8;;\:]8;id=363637;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py#245\245]8;;\

                    INFO     Completed 4 out of 6 tasks                                               ]8;id=96870;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py\runner.py]8;;\:]8;id=975754;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py#246\246]8;;\

                    INFO     Loading data from steam_clean (ParquetDataset)...                 ]8;id=965203;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=186231;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Running node: features_steam: add_basic_features() ->                      ]8;id=434636;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\pipeline\node.py\node.py]8;;\:]8;id=859669;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\pipeline\node.py#420\420]8;;\

                    INFO     Saving data to steam_prepared (ParquetDataset)...                 ]8;id=3102;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=73002;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1006\1006]8;;\

[09/15/25 22:47:25] INFO     Completed node: features_steam                                           ]8;id=429837;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py\runner.py]8;;\:]8;id=14862;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py#245\245]8;;\

                    INFO     Completed 5 out of 6 tasks                                               ]8;id=973311;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py\runner.py]8;;\:]8;id=414634;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py#246\246]8;;\

                    INFO     Loading data from vg_sales_clean (ParquetDataset)...              ]8;id=240401;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=503047;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Running node: features_vg_sales: add_basic_features() ->                   ]8;id=423533;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\pipeline\node.py\node.py]8;;\:]8;id=10253;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\pipeline\node.py#420\420]8;;\

                    INFO     Saving data to vg_sales_prepared (ParquetDataset)...              ]8;id=65078;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=988002;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1006\1006]8;;\

                    INFO     Completed node: features_vg_sales                                        ]8;id=50055;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py\runner.py]8;;\:]8;id=760936;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py#245\245]8;;\

                    INFO     Completed 6 out of 6 tasks                                               ]8;id=806213;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py\runner.py]8;;\:]8;id=642488;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py#246\246]8;;\

                    INFO     Pipeline execution completed successfully in 1.9 sec.                    ]8;id=699659;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py\runner.py]8;;\:]8;id=9437;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\runner\runner.py#119\119]8;;\

{
    'vg_sales_prepared': kedro_datasets.pandas.parquet_dataset.ParquetDataset(filepath=PurePosixPath('C:/Users/lttlk/Documents/Nueo/machinegame/data/05_model_input/vg_sales_prepared.parquet'), protocol='file', load_args={}, save_args={}),
    'games_prepared': kedro_datasets.pandas.parquet_dataset.ParquetDataset(filepath=PurePosixPath('C:/Users/lttlk/Documents/Nueo/machinegame/data/05_model_input/games_prepared.parquet'), protocol='file', load_args={}, save_args={}),
    'steam_prepared': kedro_datasets.pandas.parquet_dataset.ParquetDataset(filepath=PurePosixPath('C:/Users/lttlk/Documents/Nueo/machinegame/data/05_model_input/steam_prepared.parquet'), protocol='file', load_args={}, save_args={})
}

### Cargar y comparar RAW vs CLEAN vs PREPARED

In [5]:
games_raw = load_or_build("games_raw", "data_preparation")
games_clean = load_or_build("games_clean", "data_preparation")
games_prep = load_or_build("games_prepared", "data_preparation")

steam_raw = load_or_build("steam_raw", "data_preparation")
steam_clean = load_or_build("steam_clean", "data_preparation")
steam_prep = load_or_build("steam_prepared", "data_preparation")

vg_raw = load_or_build("vg_sales_raw", "data_preparation")
vg_clean = load_or_build("vg_sales_clean", "data_preparation")
vg_prep = load_or_build("vg_sales_prepared", "data_preparation")

def compare(df_raw, df_clean, name="dataset"):
    before = int(df_raw.isna().sum().sum())
    after = int(df_clean.isna().sum().sum())
    print(f"""== {name} ==
shape raw -> clean: {df_raw.shape} -> {df_clean.shape}
nulos  raw -> clean: {before} -> {after}
""".rstrip())

compare(games_raw, games_clean, "games")
compare(steam_raw, steam_clean, "steam")
compare(vg_raw, vg_clean, "vg_sales")

from IPython.display import display
display(games_clean.head())
display(steam_clean.head())
display(vg_clean.head())

print("prepared shapes:",
      games_prep.shape, steam_prep.shape, vg_prep.shape)

                    INFO     Loading data from games_raw (CSVDataset)...                       ]8;id=271435;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=703813;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Loading data from games_clean (ParquetDataset)...                 ]8;id=56456;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=879203;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Loading data from games_prepared (ParquetDataset)...              ]8;id=965803;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=904071;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Loading data from steam_raw (CSVDataset)...                       ]8;id=515884;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=458557;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Loading data from steam_clean (ParquetDataset)...                 ]8;id=937004;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=177025;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Loading data from steam_prepared (ParquetDataset)...              ]8;id=253786;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=975990;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Loading data from vg_sales_raw (CSVDataset)...                    ]8;id=621285;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=339237;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Loading data from vg_sales_clean (ParquetDataset)...              ]8;id=128128;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=792826;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Loading data from vg_sales_prepared (ParquetDataset)...           ]8;id=108247;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=265773;file://c:\Users\lttlk\Documents\Nueo\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

== games ==
shape raw -> clean: (14801, 4) -> (14785, 4)
nulos  raw -> clean: 0 -> 0
== steam ==
shape raw -> clean: (199999, 5) -> (199292, 5)
nulos  raw -> clean: 0 -> 0
== vg_sales ==
shape raw -> clean: (16719, 16) -> (16719, 16)
nulos  raw -> clean: 49141 -> 0

,Console,GameName,Review,Score
0,PC,Baldur's Gate 3 Early Access Review,Early Access,6
1,NS,Control: Ultimate Edition Cloud Version Review,Good,7
2,"XONE, PC, PS4",Doom Eternal: The Ancient Gods Part 1 Review,Good,7
3,"XONE, PC, PS4",Watch Dogs: Legion Review,Great,8
4,PC,Ring Of Pain Review,Great,8

   151603712  The Elder Scrolls V Skyrim  purchase    1.0  0
0  151603712  The Elder Scrolls V Skyrim      play  273.0  0
1  151603712                   Fallout 4  purchase    1.0  0
2  151603712                   Fallout 4      play   87.0  0
3  151603712                       Spore  purchase    1.0  0
4  151603712                       Spore      play   14.9  0

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8.0,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,0.0,0.0,0.0,0.0,,
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8.0,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,0.0,0.0,0.0,0.0,,

prepared shapes: (14785, 6) (199292, 7) (16719, 18)

### Checklist Fase 03
- [ ] Columnas 100% nulas eliminadas  
- [ ] Duplicados tratados  
- [ ] Nulos numéricos → 0 o mediana (según parámetros)  
- [ ] Nulos texto → cadena vacía  
- [ ] *Features* básicas agregadas (`row_na_count`, `row_na_ratio`)  
- [ ] Artefactos en `data/03_primary/` y/o `data/05_model_input/`